### PR TITLE
A script to create redirects based on renamed files in a branch  

### LINKED ISSUE #2380: Redirects: create a tool that checks for renamed files and changed paths and determines what redirect should be added
## Summary

To minimize the chance of broken links, it would be helpful to have a script that gives the writer a list of previously published files that have been renamed in a commit and suggest what the redirects should be.

This would provide the writer with guidance for adding redirects.

### LINKED ISSUE #4294: Script to apply redirects to the epas restructure branch
@josh-heyer we have completed the restructure of the EPAS docs and plan to publish it by the end of next week. Can you apply the redirects for us? The PR is https://github.com/EnterpriseDB/docs/pull/4201.

We are still actively doing clean up including fixing links, but I don't think that should interfere.

### PR DESCRIPTION
**Pull request by josh-heyer**
## What Changed?

Created script to apply redirects to the epas restructure branch. Also fix broken frontmatter in some random file.

See [the README](https://github.com/EnterpriseDB/docs/blob/bugfix/josh-heyer/4294-Script-to-apply-redirects-to-the-epas-restructure-branch/tools/user/reorg/redirects/README.md) for details

Fixes #4294
Fixes #2380

### CODE REVIEW

File: tools/user/reorg/redirects/renames-to-redirects.js [hunk 1]
```diff
@@ -0,0 +1,168 @@
...
+  }
+
+  if (!frontmatter.contents.get) {
+    console.warn("Wrong data format for frontmatter in " + sourcePath);
+    return content;
+  }
+
+  let redirects = frontmatter.contents.get("redirects");
+
+  if (sourcePath === "/workspace/docs/product_docs/docs/epas/15/database_administration/01_configuration_parameters/03_configuration_parameters_by_functionality/01_top_performance_related_parameters/05_checkpoint_segments.mdx")
```
Comment (djw-m) [inline tools/user/reorg/redirects/renames-to-redirects.js:112]: This seems remarkably specific?

File: tools/user/reorg/redirects/renames-to-redirects.js [hunk 2]
```diff
@@ -0,0 +1,168 @@
...
+  console.log(`${renames.length} renames identified, ${found} redirects identified, ${updated} files updated`);
+
+
+};
+
+const replaceRedirect = async (content, redirectPath, {sourcePath, branch}) => {
+  const frontmatterRE = /^(?<open>---\s*?\n)(?<yaml>.+?\n)(?<close>---\s*?(?:\n|$))/s;
+  const tagComment = "generated for " + branch;
+
+  const frontmatterYaml = content.match(frontmatterRE)?.groups?.yaml;
```
Comment (djw-m) [inline tools/user/reorg/redirects/renames-to-redirects.js:86]: For future reference, I've found https://www.npmjs.com/package/front-matter simplifies the front-matter processing no end.

**Review by djw-m — COMMENTED** [review]
Looks good to me, only concern is there's a super specific path in there which doesn't look cross platform - "/workspace/docs/product_docs/docs/epas/15/database_administration/01_configuration_parameters/03_configuration_parameters_by_functionality/01_top_performance_related_parameters/05_checkpoint_segments.mdx"

**Comment by drothery-edb** [comment]
@josh-heyer we have fixed all the reported broken links in the epas reorg branch. I think we are ready to try this out.

File: tools/user/reorg/redirects/renames-to-redirects.js (hunk 2 above)
Comment (josh-heyer) [reply tools/user/reorg/redirects/renames-to-redirects.js:86]: The oddly complicated approach here is purely so that I can *write the frontmatter back out* with as few disturbances as possible - ideally, the only changes are those I *intend* to make, although I'm not overly worried about changing indentation if I'm making other modifications. In particular, I don't want to mess up comments, which most normal YAML parsers throw away (as they should).

**Comment by josh-heyer** [comment]
Inaugural run, @drothery-edb : [`fbf94fc` (#4201)](https://github.com/EnterpriseDB/docs/pull/4201/commits/fbf94fcff00328b9f3014566537ed2ea3d9f2956)

**Comment by drothery-edb** [comment]
> Inaugural run, @drothery-edb : [`fbf94fc` (#4201)](https://github.com/EnterpriseDB/docs/pull/4201/commits/fbf94fcff00328b9f3014566537ed2ea3d9f2956)

Fantastic!
